### ISSUE TITLE
Remove file from list

### ISSUE THREAD

**Issue by vladanPro** [Saluev/bootstrap-file-dialog#2]
Problem is on FF, when i use remove file from list, console log result:

``` javascript
:  bootstrap.fd.js:78:0
Empty string passed to getElementById().
```

**Comment by Saluev** [comment]
I can't reproduce this behavior. Could you please give more details?

**Comment by vladanPro** [comment]
When i try to remove file what i select before but with mistake i get this ":" like on screenshot.  i don't know how else to show it, but if something else is needed just ask :)
![screenhunter_02 sep 16 17 47](https://cloud.githubusercontent.com/assets/1330505/9910009/28eb9ffe-5c9b-11e5-8cae-cfe9665e5e76.jpg)
And this is when i connect wit src folder fd.js
![screenhunter_03 sep 16 18 00](https://cloud.githubusercontent.com/assets/1330505/9910315/d5e24266-5c9c-11e5-8f1f-7ee3cbf7e6de.jpg)

**Comment by Saluev** [comment]
This was an odd Firefox bug with [FileReader API](https://developer.mozilla.org/en-US/docs/Web/API/FileReader/abort).

**Comment by vladanPro** [comment]
Its working thank you.
