### ISSUE TITLE
Problem with Safari for type of document 

### ISSUE THREAD

**Issue by vladanPro** [Saluev/bootstrap-file-dialog#3]
When i put accept: ".csv" no filtering is done and its show all files on Safari. 

```
$.FileDialog({
            accept: ".csv", //acept: MIME type of accepted files, e. g. image/jpeg
            okButton: "OK",
            cancelButton: "Close",
            title: "Upload files"
        })
```

**Comment by Saluev** [comment]
MIME type is not the same thing as file extension, have you tried `accept: "text/csv"`?

**Comment by vladanPro** [comment]
Yes that was problem on diff OS is different so i make function to see what OS is running and then use other format  
`
switch (tmp_os_name) {
            case 'MacOS':
                string_file_accept = "text/csv";
                break;
            default:
                string_file_accept = ".csv";
                break;
        }
`
