### ISSUE TITLE
Let say I have task.csv file uploaded how can I save it to server after upload?

### ISSUE THREAD

**Issue by filjoseph1989** [Saluev/bootstrap-file-dialog#7]
var file_list =ev.files

store files in file_list, how can I use file_list to pass the data to php for the php to save it in the server?

**Comment by Saluev** [comment]
Well, any method to send a string to server shall suffice. Check out, for example, this discussion on AJAX based upload: http://stackoverflow.com/questions/7431365/filereader-readasbinarystring-to-upload-files
